app/messages/blueprints/message_api_blueprint.py
from flask import Blueprint, request, jsonify
from app.messages.services.message_service import get_all_messages, get_message_by_id, increment_messsage_claps_by_id, create_message

message_api_blueprint = Blueprint(
    'messages_api', __name__, url_prefix='/api/messages')


@message_api_blueprint.get('')
def api_get_messages():
    messages = get_all_messages()
    return jsonify([vars(msg) for msg in messages]), 200


@message_api_blueprint.post('')
def api_post_message():
    json_data = request.get_json()

    author = json_data['author'] if json_data and 'author' in json_data else None
    message = json_data['message'] if json_data and 'message' in json_data else None

    added_message, error = create_message(author=author, message=message)

    if error:
        return jsonify({'message': error}), 422

    print(vars(added_message))
    return jsonify(vars(added_message)), 201


@message_api_blueprint.get('/<int:message_id>')
def api_get_message(message_id):
    message = get_message_by_id(message_id)
    if not message:
        return "", 404

    return jsonify(vars(message)), 200


@message_api_blueprint.post('/<int:message_id>/claps')
def api_post_clap_message(message_id):
    claps = increment_messsage_claps_by_id(message_id=message_id)
    if not claps:
        return "", 404

    return jsonify({'count': claps}), 201

app/messages/blueprints/message_blueprint.py
from re import template
from flask import Blueprint, render_template, request, redirect, url_for
from app.messages.services.message_service import get_all_messages, get_message_by_id, increment_messsage_claps_by_id, create_message

message_blueprint = Blueprint(
    'messages', __name__, template_folder='../templates')


@message_blueprint.get('/')
def index():
    messages = get_all_messages()
    return render_template('index.html', messages=messages)


@message_blueprint.post('/')
def add_message():
    sender = request.form['sender']
    message = request.form['message']
    added_message, error = create_message(author=sender, message=message)

    if error:
        messages = get_all_messages()
        return render_template('index.html',
                               messages=messages,
                               error=error,
                               new_sender=sender,
                               new_message=message
                               )
    return redirect(url_for('messages.index'))


@message_blueprint.get('/messages/<int:message_id>')
def message_page(message_id):
    message = get_message_by_id(message_id)
    if not message:
        return render_template('404.html', message_id=message_id)

    return render_template('message.html', message=message)

#redirect to the page where user made request (idk is this the best solution or not)
def redirect_url(default='messages.index'):
    return request.args.get('next') or \
        request.referrer or \
        url_for(default)


@message_blueprint.post('/messages/<int:message_id>/claps')
def clap_message(message_id):
    claps = increment_messsage_claps_by_id(message_id=message_id)
    if not claps:
        return render_template('404.html', message_id=message_id)

    return redirect(redirect_url())

app/messages/templates/index.html
{% extends "layout.html" %} {% block main %}
<main class="container flex-fill my-3">
    <form class="card border-secondary mb-3 create-form" data-test="send-form" action="{{url_for('messages.add_message')}}" method="POST">
        <fieldset>
            <legend class="card-header h5 border-secondary bg-dark text-light">📩 Отправить письмо</legend>
            <div class="card-body">
                <div class="mb-3 alert-danger-form" data-test="send-alert" style="display: none;">
                    <div class="alert alert-danger"></div>
                </div>

                <div class="mb-3 alert-warning-form" data-test="send-alert" style="display: none;">
                    <div class="alert alert-warning"></div>
                </div>

                <div class="mb-3 alert-success-form" data-test="send-alert" style="display: none;">
                    <div class="alert alert-success"></div>
                </div>

                <div class="mb-3">
                    <label for="sender" class="form-label">От кого:</label>
                    <input id="sender" name="sender" class="form-control" type="text" placeholder="Имя отправителя" value="{{new_sender}}" />
                </div>
                <div class="mb-3">
                    <label for="message" class="form-label">Сообщение:</label>
                    <textarea id="message" name="message" class="form-control" placeholder="Текст сообщения">{{new_message}}</textarea>
                </div>
                <div class="d-flex">
                    <button class="btn btn-outline-success ms-auto">✏️ Отправить</button>
                </div>
            </div>
        </fieldset>
    </form>

    <ul class="list-unstyled messages">
        {% for message in messages %}
        <li class="mb-3 message" data-message-id="{{message.id}}">
            <article class="card" data-test="message">
                <div class="card-body">
                    <header class="card-title d-flex">
                        <div class="text-muted" data-test="message-author">{{message.author}}</div>
                        <a href="{{url_for('messages.message_page',message_id=message.id)}}" class="card-link ms-auto" data-test="message-open">Открыть ↗️</a>
                    </header>
                    <div class="card-text" data-test="message-text">
                        {{message.message}}
                    </div>
                    <div class="d-flex">
                        <form class="ms-auto" data-test="message-clap-form" action="{{url_for('messages.clap_message',message_id=message.id)}}" method="POST">
                            <button class="btn">👏🏻 <span data-test="clap-count" class = "claps">{{message.claps}}</span></button>
                        </form>
                    </div>
                </div>
            </article>
        </li>
        {% endfor %}
    </ul>
</main>

<template id="message-template">
    <li class="mb-3 message" data-message-id="[MESSAGE_ID]">
        <article class="card" data-test="message">
            <div class="card-body">
                <header class="card-title d-flex">
                    <div class="text-muted message__author" data-test="message-author">{MESSAGE_AUTHOR}</div>
                    <a href="/messages/[MESSAGE_ID]" class="card-link ms-auto message__link" data-test="message-open">Открыть ↗️</a>
                </header>
                <div class="card-text message__text" data-test="message-text">
                    {MESSAGE_TEXT}
                </div>
                <div class="d-flex">
                    <form class="ms-auto claps__form" data-test="message-clap-form" action="/messages/[MESSAGE_ID]/claps" method="POST">
                        <button class="btn">👏🏻 <span data-test="clap-count" class = "claps">{MESSAGE_CLAPS}</span></button>
                    </form>
                </div>
            </div>
        </article>
</template>
<script src="{{url_for('static',filename='index.js')}}"></script>
{% endblock %}

app/messages/templates/message.html
{% extends "layout.html" %} {% block main %}
<main class="container flex-fill my-3 message" data-message-id="{{message.id}}">
    <article class="card" data-test="message">
        <div class="card-body">
            <header class="card-title d-flex">
                <div class="text-muted" data-test="message-author">{{message.author}}</div>
            </header>
            <div class="card-text" data-test="message-text">
                {{message.message}}
            </div>
            <div class="d-flex">
                <form class="ms-auto" data-test="message-clap-form" action="{{url_for('messages.clap_message',message_id=message.id)}}" method="POST">
                    <button class="btn">👏🏻 <span data-test="clap-count" class = "claps">{{message.claps}}</span></button>
                </form>
            </div>
        </div>
    </article>
</main>
<script src="{{url_for('static',filename='message.js')}}"></script>
{% endblock %}